[workspace]
resolver = "2"
members = [
    "robot",
    "robot_new",
    "surface",
    "common",
    "networking",
    "motor_math",
    "stable_hashmap",
    "waterlinked",

    "crates/ecs_sync",
    "crates/error",
    "crates/ctrlc",
    "crates/over_run",
    "crates/units",
    "crates/depth_hold",
    "crates/stabilize",
    "crates/water_linked_ugps",
    "crates/thruster",
    "crates/pwm_ctrl",
    "crates/can_ctrl",
    "crates/hw_mon",
    "crates/voltage_mon",
    "crates/video_streamer",
    "crates/bluerobotics_depth",
    "crates/navagator_pi_hat",
    "crates/ui_egui", "crates/user_input", "crates/neopixel",
]

# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

# Enable high optimizations for dependencies (incl. Bevy), but not for our code:
[profile.dev.package."*"]
opt-level = 3

[profile.release]
debug = true
