[robot]
name = "Dark Shark"
port = 44445


#
# Declare Avaible Hardware
#

[[interfaces]]
name = "PWM"
hardware = "pca9685"
i2c_bus = 3
i2c_address = 0x40

[[interfaces]]
name = "ADC"
hardware = "ads1115"
i2c_bus = 1
i2c_address = 0x48

[[interfaces]]
name = "Power Sense"
hardware = "bluerov_powersense"
data = "ADC"

[[interfaces]]
name = "IMU"
hardware = "icm20602_spi"
spi_bus = 1
spi_cs = 2

[[interfaces]]
name = "MAG"
hardware = "mmc5983_spi"
spi_bus = 1
spi_cs = 1

[[interfaces]]
name = "Depth"
hardware = "ms5937"
i2c_bus = 6
i2c_address = 0x76

[[interfaces]]
name = "LEDs"
hardware = "neopixel_spi"
spi_bus = 0
spi_cs = 0

[[interfaces]]
name = "Leak"
hardware = "leak"
gpio = 27
active = "High"

# TODO: Power Sense


#
# Declare Thruster Configuration
#

[thruster_config]
type = "X3d"
seed_thruster = { position = [
  0.19,
  0.21,
  0.09,
], orientation = [
  -0.254,
  0.571,
  -0.781,
], direction = "CounterClockwise" }

center_of_mass = [0.0, -0.035, 0.0]
thruster_amperage_budget = 25.0
thruster_jerk_limit = 40.0


#
# Declare Thrusters
#

[[thrusters]]
name = "FrontRightBottom"
type = "T200"
interface = "PWM"
pwm_channel = 0

[[thrusters]]
name = "BackRightBottom"
type = "T200"
interface = "PWM"
pwm_channel = 1

[[thrusters]]
name = "BackRightTop"
type = "T200"
interface = "PWM"
pwm_channel = 2

[[thrusters]]
name = "FrontLeftTop"
type = "T200"
interface = "PWM"
pwm_channel = 3

[[thrusters]]
name = "FrontLeftBottom"
type = "T200"
interface = "PWM"
pwm_channel = 4

[[thrusters]]
name = "BackLeftBottom"
type = "T200"
interface = "PWM"
pwm_channel = 5

[[thrusters]]
name = "BackLeftTop"
type = "T200"
interface = "PWM"
pwm_channel = 6

[[thrusters]]
name = "FrontRightTop"
type = "T200"
interface = "PWM"
pwm_channel = 7


#
# Declare Thruster Force data
#

[[thrust_data]]
name = "T200"
path = "motor_data.csv"

#
# Declare Servos
#

[[servo_config.servos]]
name = "FrontCameraRotate"
interface = "PWM"
pwm_channel = 15
cameras = ["Front"]

[[servo_config.servos]]
name = "Claw1"
interface = "PWM"
pwm_channel = 14
cameras = ["Front"]

[[servo_config.servos]]
name = "Claw2"
interface = "PWM"
pwm_channel = 13
cameras = ["Front"]

[[servo_config.servos]]
name = "Claw3"
interface = "PWM"
pwm_channel = 12
cameras = ["Front"]


#
# Declare Cameras
#

[[cameras]]
name = "Front"
type = "H264"
path = "/dev/video2"
#transform = { position = { x = 0.0, y = 1.0, z = 0.0 }, rotation = { yaw = 0.0, pitch = 0.0, roll = 0.0 } }

[[cameras]]
name = "Top"
type = "H264"
path = "/dev/video6"
#transform = { position = { x = 0.0, y = 0.0, z = 1.0 }, rotation = { yaw = 0.0, pitch = -90.0, roll = 0.0 } }

[[cameras]]
name = "A"
type = "H264"
path = "/dev/video10"
#transform = { position = { x = 0.0, y = 0.0, z = -1.0 }, rotation = { yaw = 0.0, pitch = 90.0, roll = 0.0 } }

[[cameras]]
name = "B"
type = "H264"
path = "/dev/video10"
#transform = { position = { x = 0.0, y = -1.0, z = 0.0 }, rotation = { yaw = -180.0, pitch = 0.0, roll = 0.0 } }

[[cameras]]
name = "C"
type = "H264"
path = "/dev/video18"
#transform = { position = { x = 1.0, y = 0.0, z = 0.0 }, rotation = { yaw = -90.0, pitch = 0.0, roll = 0.0 } }


#
# Setup Control System
#

[control.ekf]
# TODO: Options for pose filtering

[control.depth_hold]
# source = "Depth"
kp = 100.0
ki = 5.0
kd = 1.5
kt = 5000.0
max_integral = 10.0

[control.stabilize.pitch]
kp = 0.5
ki = 0.25
kd = 0.15
kt = 5.0
max_integral = 60.0

[control.stabilize.roll]
kp = 0.3
ki = 0.15
kd = 0.1
kt = 3.5
max_integral = 30.0

[control.stabilize.yaw]
kp = 0.15
ki = 0.07
kd = 0.12
kt = 5.0
max_integral = 20.0
