[package]
name = "waterlinked"
version = "0.1.0"
edition = "2021"


[dependencies]
common = { workspace = true }
networking = { workspace = true }
motor_math = { workspace = true }

bevy = { workspace = true, default-features = true, features = [
  "wayland",
  "dynamic_linking",
] }

tracing = { workspace = true }
tracing-subscriber = { workspace = true }

anyhow = { workspace = true }

reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
csv = { workspace = true }
tokio = { workspace = true }
bevy-tokio-tasks = { workspace = true }

egui = { workspace = true }
egui_plot = { workspace = true }
bevy_egui = { workspace = true }
bevy-inspector-egui = { workspace = true }
nalgebra = { workspace = true }

adskalman = { workspace = true }
minikalman = { version = "0.6", features = ["std"] }
kfilter = "0.3.1"

[dev-dependencies]
rand = { workspace = true }
rand_distr = { workspace = true }
